#!/bin/sh
# Docker long-running operations (pull/build) need higher timeouts
# rpcd: ubus RPC calls through dockerman
# uhttpd: LuCI CGI streaming responses

uci -q get rpcd.@rpcd[0] && {
    uci set rpcd.@rpcd[0].timeout=300
    uci commit rpcd
}

uci -q get uhttpd.main && {
    uci set uhttpd.main.network_timeout=300
    uci commit uhttpd
}

exit 0
