#!/bin/sh
# Docker long-running operations (pull/build) need higher timeouts
# rpcd: ubus RPC calls through dockerman (default 30s)
# uhttpd script_timeout: CGI/Lua handler execution (default 60s)
# uhttpd network_timeout: network I/O (default 30s)

uci -q get rpcd.@rpcd[0] && {
    uci set rpcd.@rpcd[0].timeout=300
    uci commit rpcd
}

uci -q get uhttpd.main && {
    uci set uhttpd.main.script_timeout=3600
    uci set uhttpd.main.network_timeout=300
    uci commit uhttpd
}

exit 0
