name: Daily Build Scheduler (JD Cloud IPQ60xx)

on:
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  trigger-build:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release WRT (JD Cloud)
        run: |
          gh workflow run release_wrt.yml --ref ipq60xx --repo ${{ github.repository }}
