name: Daily Build Scheduler

on:
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch:
    inputs:
      model:
        description: Build Model
        required: false
        default: all
        type: choice
        options:
          - all
          - release_wrt
          - x64_immwrt

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  trigger-release:
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger JD Cloud IPQ60xx
        if: inputs.model == 'all' || inputs.model == 'release_wrt' || github.event_name == 'schedule'
        run: |
          gh workflow run release_wrt.yml --ref ipq60xx --repo ${{ github.repository }}

      - name: Trigger X86_64
        if: inputs.model == 'all' || inputs.model == 'x64_immwrt' || github.event_name == 'schedule'
        run: |
          gh workflow run release_wrt.yml --ref x86_64 --repo ${{ github.repository }}
