name: Daily Build Scheduler (x86_64)

on:
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  trigger-build:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release WRT (x86_64)
        run: |
          gh workflow run release_wrt.yml --ref x86_64 --repo ${{ github.repository }}
